name: Pull Request Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  verify-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./.github/actions/setup-project

      - name: Lint code
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Build project
        run: npm run build
